name: simple_todo
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: João Perin <joaovperin@live.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
